# This .gclient is generated by Chromium build script 04/24/17 09:06:52
#> chromium c65d61b8d34b256e7ede213128f9b426ac2ba714 1492605520
#> skia a14feb3bc04579ec19f92180782bc12d04728750 1482810394
#> v8 9f70fbc314b4ca4cbb344bf2fff9a5d906574ad0 1481764990
#> boringssl 3cab5572b1fcf5a8f6018529dc30dc8d21b2a4bd 1466099019

solutions = [
{ 
  "managed": False,
  "name": "src",
  "url": "http://gerrit.mediatek.inc:8080/alps/chromium.git@c65d61b8d34b256e7ede213128f9b426ac2ba714",
  "custom_deps": {
    "src": "http://gerrit.mediatek.inc:8080/alps/chromium.git@c65d61b8d34b256e7ede213128f9b426ac2ba714",
    "src/third_party/skia": "http://gerrit.mediatek.inc:8080/alps/chromium/third_party/skia.git@a14feb3bc04579ec19f92180782bc12d04728750",
    "src/v8": "http://gerrit.mediatek.inc:8080/alps/chromium/v8.git@9f70fbc314b4ca4cbb344bf2fff9a5d906574ad0",
    "src/third_party/boringssl/src": "http://gerrit.mediatek.inc:8080/alps/chromium/third_party/boringssl/src.git@3cab5572b1fcf5a8f6018529dc30dc8d21b2a4bd",
  },
  "deps_file": ".DEPS",
  "safesync_url": "",
},]
target_os = ['android']

